/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'carolinabarros' at '17-11-2016 23:16' with Gradle 3.1
 *
 * @author carolinabarros, @date 17-11-2016 23:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
